resolver: lts-21.14
packages:
- 'cborg'
- 'serialise'
- 'binary-serialise-cbor'
- 'cbor-tool'
- 'cborg-json'

flags:
  serialise:
    newtime15: true

extra-deps:
- commit: f143eae94b79fdbc963640ecdadb5d222be6d7ef
  git: "https://github.com/well-typed/dupIO.git"
  subdirs:
  - .
